### ISSUE TITLE
Keyboard won't work with major browsers 

### ISSUE THREAD

**Issue by k4ever** [maliit/keyboard#50] opened 2021-06-06 13:37 UTC
I'm using the Maliit Keyboard (2.x) with KDE Neon in a Plasma desktop Wayland session. The keyboard works great with desktop elements, but doesn't work with any major web browser (Firefox, Chrome, Opera, etc). Is there a way to make these browsers recognize the keyboard in Wayland?

**Comment by nicolasfella** [comment] 2021-06-12 18:55
This has little to do with the maliit keyboard. The issue is that these programs run under XWayland and/or lack support for the text-input Wayland protocol

**Comment by mitlaw2004** [comment] 2021-06-12 22:33
Is working with firefox, but in wayland mode. I have no problem with kde 5.22.

**Comment by mitlaw2004** [comment] 2021-06-12 22:39
Launch with
 MOZ_ENABLE_WAYLAND=1 firefox
 Or put 
MOZ_ENABLE_WAYLAND=1
 In /etc/environment, or as your distro indications.
I use Archlinux.

**Comment by KAMiKAZOW** [comment] 2021-06-29 16:43
Can you please close this report? It's a problem with those browsers, not Maliit.

**Comment by k4ever** [comment] 2021-06-30 03:00
I've got Maliit to work with Firefox using what mitlaw2004 posted. However, I can't get it to work with Chrome, Chromium, or Microsoft Edge for Linux, even when using the --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime flags. Wayland is clearly being used, not XWayland, but Maliit will not show. I submitted a bug report for Chromium. 

Before I close this, are you positive this is not a Maliit issue? Also, is there a way to manually launch the Maliit keyboard?

**Comment by bhush9** [comment] 2021-09-20 03:59
Yes it can be closed here. It is most likely issue with either application or compositor, KWin for example supports the text-input v2 and v3 protocols for compositor to app communication, if chromium doesn't support either than its chromium issue or it might be KWin issue but definitely not maliit here.

**Closed** 2021-09-20 04:00 UTC
